-- Even at ~650-750 words, chapters only produced about 1.5 screens of scroll on a
-- phone-sized viewport (measured: 716 words ~= 1084px of content on a 717px
-- viewport). Expand each chapter further, to roughly 1900-2000 words, so there's
-- genuinely 4+ screens to scroll through and the progress bar has real room to move.

-- ========== THE LAST LETTER (forgiveness) ==========
update public.story_chapters
set body = $$Neither of them could say anymore exactly how it started. That was the strange part — nine years later, if you'd asked either brother to point to the moment everything went wrong, they'd have given you two different answers, and neither would have been the whole truth.

What they agreed on was this: it was a Sunday, their mother's birthday, the kind of dinner that happened every year without anyone having to plan it. The good plates were out, the ones with the thin gold rim that only came down from the cabinet twice a year. Their father was carving something he'd been proud of all afternoon, narrating the process to nobody in particular the way he always did when he cooked. Their mother had put out the good napkins too, cloth instead of paper, which she did only when she wanted the occasion to feel like an occasion.

Somewhere between the second helping and the coffee, a comment got made — about money, or about their father's health, or about who had shown up more over the years to help around the house — and it landed wrong. Daniel remembers it as being about money. Marcus, when he thinks about it at all, remembers it as being about something their father had said first, that Daniel had misheard and redirected at him. Nine years later, it hardly matters which version is closer to true.

Marcus said something he thought was a joke, the kind of sharp-edged teasing that had always passed between them as affection when they were kids. Daniel didn't take it as one. Marcus, reading the room wrong, doubled down instead of walking it back, the way people do when they'd rather be right than kind, when some old competitive instinct from childhood takes over and makes backing down feel like losing.

Daniel stood up from the table hard enough that his chair scraped the floor loud enough to make his mother flinch. He said something short and sharp about how nobody ever had to guess what Marcus really thought of them, how at least he was consistent that way, and left before dessert — actually left, got in his car and drove home to an apartment he'd shared with his girlfriend at the time, who took one look at his face and didn't ask any questions until the next morning.

Their mother cried a little that night, after everyone had gone, though she wouldn't admit it the next morning when Daniel called to apologize to her, if not to his brother. Their father just shook his head over the leftover cake and said they'd sort it out, the way brothers always did, the way he and his own brother had sorted out worse things decades earlier. He said it every year after that, too, for a while, with less and less conviction each time.

What followed wasn't a single decision to stop speaking — nothing so clean as that. It was smaller and slower: a birthday missed on purpose the following spring, a text left on read for three days and then not answered at all, a wedding invitation eighteen months later that Daniel sent to the whole extended family except, unmistakably, deliberately, to Marcus. Neither of them called to talk about any of it directly. Both of them noticed everything.

By the second year, avoiding each other had become its own kind of routine, with its own unspoken rules. They went to the same Thanksgiving at different times, arriving and leaving in shifts their mother coordinated without ever saying out loud what she was doing. They asked about each other through her, carefully, the way you'd ask about a distant acquaintance rather than a brother. "How's Marcus doing?" Daniel would ask, almost casually, while helping her dry dishes. "He's fine. Busy," she'd say, and neither of them would push further, because pushing further meant admitting how strange the whole arrangement had become.

Cousins started picking sides without meaning to, the way families do — not dramatically, just in small logistical ways, in who got invited to what, in whose version of events got repeated at gatherings neither brother attended together. Their grandmother, before she passed, used to ask about it at every visit, in her nineties and increasingly baffled by the whole thing. "You used to share a room," she'd say, as if that settled something. "You used to be inseparable."

There were moments that could have broken it, plenty of them, scattered across nine years like stepping stones neither brother chose to use. When their father had his first health scare — a fall in the garage, a night in the ER that turned out, thankfully, to be nothing serious, just a bad bruise and an overnight observation — Daniel almost called. He got as far as finding the number, his thumb actually hovering over it, before deciding his father would tell him if it were truly bad, and if he called now, out of nowhere, after everything, it would look like he only cared because of the timing, like he was keeping score and waiting for an opening. He put the phone down and told himself there'd be another moment, a better one, when the reason for calling wouldn't be tangled up with the silence itself. There never quite was.

Once, three years in, they ran into each other at a gas station forty minutes from either of their homes, an absurd coincidence that felt almost engineered by whatever force enjoys putting estranged siblings in the same place at the wrong time. Marcus was filling up his tank two pumps down. Daniel saw him first, recognized the set of his shoulders before he even turned around, and made the immediate, instinctive decision to look at his own gas cap very intently until Marcus finished and drove away. He sat in his car afterward for a full five minutes before he trusted himself to drive.

Marcus had his own almost-moments too — a good year at work, a promotion he'd worked toward for years, that he wanted to tell someone who'd actually understand what it had taken to get there, someone who'd known him back when he was nowhere close to that kind of success. A night alone in a new apartment in a new city, after the move, when the quiet made him think of being a kid again, sharing a room, arguing over nothing that mattered, falling asleep mid-argument the way brothers do. Each time, he thought about picking up the phone. Each time, the thought of how strange it would sound after so long — "Hey, it's your brother, I know it's been years" — was enough to put it off one more week, and then one more year, until the years had stacked up into something that felt too heavy to lift with a single phone call.

Their mother stopped asking either of them directly after the third Christmas passed without a word between them, not even a text. She'd learned, the hard way, that bringing up one brother to the other only shortened whatever conversation she was trying to have. She kept both their numbers in her phone under their first names, no distinguishing marks, no note to remind her of the estrangement, as if refusing to acknowledge on paper — or on a screen — that there was anything unusual about two brothers who hadn't spoken in nearly a decade.

Nine years is a long time to let one Sunday dinner define two people's relationship. Long enough that new colleagues, new friends, even Daniel's own kids as they got old enough to ask questions, didn't know he had a brother at all unless someone else mentioned it first, usually their grandmother, usually followed by an awkward silence and a change of subject. Long enough that the specific words said at that table had blurred and softened in memory, worn down like a stone in a river, until neither of them could have told you exactly what was said — only that it had been enough, at the time, to feel unforgivable, and that the feeling itself had long since outlived whatever had caused it.$$
where chapter_number = 1
  and story_id = (select id from public.stories where title = 'The Last Letter');

update public.story_chapters
set body = $$It arrived on a Tuesday, the kind of unremarkable Tuesday that gives no warning about what it's about to hold. Daniel had come home late from work, tired in the specific way that made the mail feel like one more chore rather than anything worth looking forward to — bills, a flyer for a restaurant that had closed two years ago and apparently hadn't updated its mailing list, a reminder card from his dentist's office, the usual accumulation of paper that means nothing until, occasionally, it means everything.

And then, underneath all of it, an envelope with no return address, his name written across the front in handwriting he hadn't seen in nine years but recognized instantly anyway, before his brain had even consciously processed why it looked familiar. Some things don't fade the way you expect them to. He'd have thought, if you'd asked him the week before, that nine years would be enough to make a handwriting sample unfamiliar. It wasn't.

He stood in the entryway for a long moment before he opened it, keys still in his other hand, coat still on, the rest of the mail forgotten on the small table by the door where it usually landed the second he walked in. Some part of him already knew who it was from before he'd even turned the envelope over to check. The postmark was from three states away — Marcus had moved, then, at some point in the last nine years, another thing Daniel hadn't known about his own brother, another small proof of how much distance had accumulated beyond just the emotional kind.

Inside was a single sheet of paper, folded in thirds, shorter than he expected a letter to be after nine years of silence. No return address on the letter itself either, no long explanation, no accounting of who had done what to whom across nearly a decade, no apology laid out like evidence in a case Daniel hadn't fully realized was still open in his brother's mind, if it had ever really closed in his own.

Just: "I miss my brother. Call me when you can. — M"

He read it standing in the entryway, coat still on. Then he read it again sitting at the kitchen table, coat finally off, draped over the back of the chair, the letter flat in front of him like something that might disappear if he looked away too long. He read it a third time before he let himself put it down, and even then he kept glancing back at it every few minutes, as if the words might have changed, might say something more complicated than what they actually said, something that would give him a reason not to feel what he was starting to feel.

He called his wife into the kitchen, wordlessly, just held the letter out to her without explanation. She read it once, looked up at him, and asked the only question that mattered: "Are you going to call him?"

"I don't know yet," he said, which was true, though even as he said it he suspected it wasn't going to hold up for very long.

She didn't push. She'd heard enough over the years — never a full accounting, Daniel wasn't built that way, but enough fragments over enough years to understand there was a brother-shaped absence in her husband's life that he didn't talk about directly but that showed up sideways, in the careful way he answered his kids' occasional questions about family, in a certain look that crossed his face at other people's family gatherings when siblings were mentioned.

Nine years of reasons not to call — pride, mostly, if he was honest with himself, though he'd have called it something more dignified at the time. The fear of how strange it would sound, reaching out after so long, like showing up uninvited somewhere you used to belong. The vague, comfortable sense that too much time had passed for anything to be salvaged, which was easier to believe than the alternative, which was that the salvaging had simply never been attempted. All of it suddenly felt very hard to explain, even to himself, sitting there with eleven words in his brother's handwriting undoing arguments he'd spent years building.

He thought about their mother's birthday dinner, the one that started it all, and found he genuinely could not remember anymore what the actual comment had been — his or Marcus's, whoever had said it first — only the shape of the feeling it left behind: being talked down to, being dismissed, the particular sting of it coming from someone who was supposed to know him better than almost anyone. Nine years later, the feeling had outlived the memory of its own cause, had become a kind of scar tissue he'd built his understanding of his brother around without ever checking if the original wound underneath still matched the story he told himself about it.

He thought about the wedding he hadn't invited Marcus to, a decision that had felt righteous at the time, almost satisfying in a petty way he wasn't proud of, and now, with the letter in front of him, felt small in a way he didn't like admitting even privately. He thought about a specific memory from when they were nine and eleven, building an elaborate blanket fort in their parents' living room that had taken up the entire space for three days, their mother stepping around it good-naturedly while it lasted, the two of them sleeping in it two nights running with a flashlight and a stack of comic books, before an argument over something neither of them could now recall had ended in the fort's dramatic, mutual destruction. Even then, the friendship underneath had survived. He wondered when exactly it had stopped being able to.

He thought about his own kids, who'd occasionally asked, with the particular bluntness of children, if they had an uncle on their father's side, and the vague answer he'd always given — "sort of, it's complicated" — that had never felt like enough of an explanation even as he said it, that had always left a small guilty residue afterward, a sense of having failed to give them something they were owed.

He didn't call that night. He told himself it was because it was late, because Marcus was probably asleep by now in whatever time zone he'd landed in, because a call like this deserved to be made properly, in daylight, with a clear head, not rushed at the tail end of an exhausting day when he might say the wrong thing out of sheer fatigue. All of that was true, as far as it went. It was also true that he needed the night to sit with the letter, to let nine years of built-up distance start to soften at the edges before he tried to close it entirely in a single conversation.

He propped the letter against the lamp on his nightstand where he'd see it first thing in the morning, half-worried that if he put it away in a drawer, out of sight, he'd find some new reason to let it wait another year, the way he'd found reasons for eight years running. He fell asleep slowly, thinking about his brother's handwriting, unchanged after nearly a decade, and the eleven words that had undone more imagined conversations — the hundred different ways he'd pictured this moment going, badly, over the years — than he would have thought possible from a single, short, unremarkable-looking sheet of paper.$$
where chapter_number = 2
  and story_id = (select id from public.stories where title = 'The Last Letter');

update public.story_chapters
set body = $$He picked up the phone three separate times the next morning before he actually dialed. Twice he got as far as pulling up the number — still saved under "Marcus," no last name, the way it had been since they were teenagers and first got cell phones, back when saving a sibling's full name in your contacts would have seemed strangely formal — before setting the phone face-down on the counter and finding something else urgent to do instead. Coffee needed making, though he'd already made a cup twenty minutes earlier that had gone cold and untouched by the sink. Dishes needed washing, though there were only three of them. Nine years had apparently not cured him of finding small, manufactured tasks to avoid a hard conversation.

The third time, he didn't let himself stop to think about it. He dialed before the part of his brain that specialized in reasons-not-to could catch up and mount its usual defense.

It rang twice. Then a voice that was older than he remembered, rougher at the edges in a way nine years will do to anyone, but unmistakably the same voice underneath it, said, "Hello?"

"It's me," Daniel said, and immediately felt foolish, as if there were any real doubt about who "me" might be, calling from this number, after this many years, exactly one day after a letter with eleven words on it had arrived at his door.

There was a pause on the other end — not a cold one, he could tell even over the phone, just the sound of someone recalibrating, the way you do when something you've hoped for finally happens and you're not entirely ready for it despite months, maybe years, of hoping. "I wasn't sure you'd call," Marcus said finally, and there was something thick in his voice that he cleared before continuing. "I wasn't sure I would've, either, honestly. If it'd been me getting the letter instead of sending it."

"I almost didn't," Daniel admitted. "I read it about six times first. My wife thinks I stared at it for twenty minutes before I even opened it."

Marcus laughed at that, a short surprised sound, and something in Daniel's chest loosened slightly at hearing it — a laugh he recognized, unchanged, running underneath nine years of separate lives like a thread that had never actually been cut, only stretched further than either of them had thought it could go without snapping.

They started with safe ground, the way people do when they're both aware of how much unsteady ground lies just beyond it. Their father's health, which had been fine for a while now, no more scares since the fall in the garage that Daniel had almost called about and hadn't. Their mother's garden, which had apparently expanded considerably, and which Marcus seemed to know more about in detail than Daniel did, having called her more regularly over the years than Daniel had realized, a small fact that stung faintly before Daniel reminded himself he had no standing to feel jealous about who had stayed closer to their mother during the years he himself had let slip past.

They traded small, careful facts back and forth like they were testing the weight the conversation could hold before either of them leaned on it too hard — Marcus's move three states over, for a job he described with real enthusiasm, the first time in longer than Daniel could remember hearing his brother sound genuinely excited about anything. Daniel's kids, ages and grades and the specific personality quirks that make each child different from the last, the kind of detail you only share with someone you expect to actually remember it.

Then, without either of them quite deciding to, the conversation loosened further, the careful testing giving way to something closer to how it used to be. Marcus mentioned a job he'd taken two years back, a promotion that had meant a great deal to him, the kind of thing he would have called Daniel about immediately once, back before, and there was a beat of something like grief in the gap where that call should have happened and hadn't — a small, specific mourning for a version of the last nine years that neither of them had gotten to have. Daniel told him about his kids' occasional questions, about the vague answer he'd always given them, about how it had never sat right with him, and heard Marcus go quiet for a moment on the other end, absorbing that.

"I've got a kid too, you know," Marcus said. "Well — not yet. But soon. Couple months."

Daniel sat down hard on the edge of his bed, the news landing somewhere between joy and a fresh, sharper grief — nearly a decade of missed context arriving all at once, a brother's entire adult life he'd only get the highlight reel of now, filled in secondhand and years late. "You're going to be a dad," he said, and heard his own voice catch slightly. "Marcus. That's — I'm really happy for you. I mean that."

"I want him to know his uncle," Marcus said, quieter now. "That's part of why I wrote the letter, if I'm honest. I didn't want to explain to my kid someday why there's this whole side of the family he's never met, this whole complicated non-answer, the way I know Mom's had to give people over the years."

Twenty minutes in, they were talking the way they used to — overlapping, interrupting, finishing sentences the other had started, laughing at something that wouldn't have been funny to anyone who hadn't grown up in the same house eating the same terrible casseroles their father used to experiment with on Sunday nights. It was, against every expectation Daniel had walked into the call with, almost easy, in a way that made the nine years feel, for a strange suspended moment, almost beside the point.

Neither of them brought up the dinner directly. Neither of them brought up the nine years in full — not the missed wedding, not the birthday cards that had stopped coming from both directions, not the specific comment that had started all of it, which Daniel still couldn't fully remember and, he realized somewhere around the forty-minute mark, no longer particularly needed to. Some things, it turned out, didn't require the full accounting to be set down and forgiven. They just required someone to go first, and then required the other person to meet them there without demanding a complete itemized apology for every year in between.

Before they hung up, nearly an hour after the call started, Marcus said, quieter than the rest of the conversation had been, something almost hesitant in it. "I really did just want to see if we still had this. Whatever this is. I wasn't sure, writing the letter, if there'd be anything left to find."

"We still have it," Daniel said, and found he meant it more fully than he'd expected to when he'd first seen the letter propped against his lamp the night before, uncertain then whether a single phone call could possibly undo what nine years had built up. "I don't think it ever actually went anywhere. I think we just both got very good at pretending it had."

They talked about getting together soon, properly, in person, with their parents there to see it — no fixed date yet, but the kind of loose, forward-looking plan that felt real rather than merely polite, the kind you make when you actually intend to follow through rather than the kind you make to end a conversation gracefully. Daniel promised to call their mother that same evening, to tell her before Marcus did, a small private joke between them about who got to deliver the good news first, the kind of sibling competitiveness that felt, for once, entirely harmless.

When Daniel finally set the phone down, the quiet of his kitchen felt different than it had the day before, less like an empty room and more like a held breath finally let out. Nine years is a long silence to carry around, longer than either of them would have chosen if you'd asked them at any point during it. It turned out, in the end, to need only one letter, and then only one sentence spoken out loud, to start coming undone.$$
where chapter_number = 3
  and story_id = (select id from public.stories where title = 'The Last Letter');

-- ========== THE COMMUNITY GARDEN (hope) ==========
update public.story_chapters
set body = $$The lot had been fenced off for so long that most people on the block had stopped seeing it entirely — the kind of empty space that becomes part of the scenery, mentioned only when visitors asked what used to be there and nobody could quite remember anymore, or remembered different, conflicting versions of the same vague history.

It had been a corner store once, decades back, the kind of place that sold milk and cigarettes and lottery tickets and knew everyone's name, and then briefly an auto shop after the store closed, and then nothing at all after a fire nobody talked about in much detail — an old wiring problem, most people said, though there were other rumors too, less charitable ones, that had never been confirmed and had mostly just faded along with everything else about the place. The building came down not long after the fire, deemed unsafe to leave standing, and the city never got around to doing anything with the resulting empty rectangle beyond fencing it off and, eventually, forgetting it existed at all.

What was left after all that was a rectangle of cracked concrete and stubborn weeds, boxed in by chain-link that had rusted to the color of old pennies, a padlock on the gate that had probably been changed once or twice over the years by some city worker following a checklist, without anyone higher up ever revisiting whether the lot needed to stay locked at all, or why.

Six years of that. Six years of broken glass catching the light at certain times of day, glinting through the weeds like something almost pretty if you didn't know what it actually was. Six years of the same three shopping carts slowly getting buried under growth that came back taller each summer no matter how many times the city's contracted mowing crew came through with weed whackers to keep it from getting completely out of hand. Six years of a chain-link fence doing the one job anyone still cared about it doing, which was keeping people out of a space nobody had found a use for and, increasingly, nobody could imagine a use for either.

Rosa noticed it every day walking her daughter to school, the way you notice something without really seeing it, the way a piece of furniture you've had for years disappears into the background of your own home. She'd moved to the block nine years earlier, right around when the fire happened, actually, and had absorbed the lot's existence as simply how that corner looked, the same way she'd absorbed the crack in the sidewalk two houses down that everyone stepped over without thinking.

Dennis noticed it from his porch two doors down, where he'd sit some evenings after retiring from thirty-one years driving a city bus, a coffee going cold in his hand an hour before he remembered to drink it, more time on his hands now than he entirely knew what to do with, more evenings than he'd expected spent simply watching the street.

Yusuf noticed it because his apartment window looked directly onto it, and some nights the streetlight through the chain-link threw a shadow pattern across his ceiling that he'd stopped finding strange only because he'd stopped really looking at it, the way you stop hearing a clock ticking in a room you spend enough time in. He'd come to the country twelve years earlier, worked his way from a stock room to running the hardware store two blocks over, and had developed, along the way, strong and mostly unsolicited opinions about soil quality that his customers had learned to either welcome or politely redirect.

The three of them had exchanged nothing more than waves for years — the kind of nodding familiarity that comes from sharing a block without sharing anything else, without ever quite finding the occasion to become more than neighbors who recognized each other's cars. It was Rosa, waiting at a stop sign with Dennis one evening while a slow line of cars passed through the intersection, who said it first, half as a joke, mostly just filling silence while they waited: "Somebody ought to just take that fence down and plant something in there. Beats looking at broken glass every morning."

Dennis laughed, the easy laugh of someone humoring a stranger's small talk, the way you laugh at something you don't expect to go anywhere beyond that moment at the crosswalk. Then, a beat later, walking the rest of the way home, he found himself actually turning the idea over, and by the time he reached his own porch he'd stopped laughing and started wondering. The next time he saw Rosa, a few days later, he said, almost sheepishly, "You know, I actually don't know why nobody has. Done something with that lot, I mean. Six years is a long time for nothing to happen."

It took a month of phone calls to find out why nothing had happened, and the answer, once they finally got it, was almost disappointingly simple: the lot, it turned out, technically belonged to the city, inherited through some tax default years back after the original owner had walked away rather than deal with the insurance aftermath of the fire, and then filed away and forgotten in the specific way that unglamorous municipal property so often is, buried in a database somewhere between more urgent priorities. There was no active plan for it, no development on the books, nothing standing in the way except the plain fact that nobody had ever actually asked.

Rosa made the first call, mostly out of stubbornness once she'd started and didn't want to be the one who let the idea die after bringing it up. She got transferred four times before she found someone in the parks department who seemed to actually know what she was talking about, a tired-sounding but genuinely helpful woman named Patrice, and even then it took another three weeks of follow-up emails, forms, and one moderately absurd phone call about liability insurance before anyone would commit to anything concrete.

Dennis, meanwhile, went to a community board meeting neither of them had ever attended before, a fluorescent-lit room in the back of the library that maybe fifteen people showed up to on a good month, and sat through ninety minutes of unrelated business — a dispute about parking permits, a lengthy discussion of a proposed crosswalk — to get two minutes at the very end to make the case for the lot. He came home afterward and told Rosa it had gone "fine, I think," in the noncommittal tone of a man who wasn't entirely sure what he'd just accomplished.

Yusuf, for his part, started drafting an actual plan without anyone asking him to, the kind of unsolicited thoroughness that came naturally to him — what could realistically grow there given the likely soil conditions after a fire and years of neglect, what the lot would need in terms of cleanup before anything useful could go in the ground, roughly how much all of it might cost if they wanted to do it properly rather than just symbolically. He brought three pages of handwritten notes to the first meeting the three of them actually sat down to have together, at Dennis's kitchen table, and Rosa remembers thinking, looking at those notes, that this might actually happen.

The city clerk who finally, weeks later, handed over the key seemed almost bemused by the whole request, as if community gardens were an idea from some earlier decade she vaguely remembered being popular once and hadn't expected to encounter again. "It's yours," she said, sliding a single brass key across the counter with the particular indifference of someone processing the hundredth mildly unusual request of her week. "Try not to hurt yourselves on the glass in there. And you didn't hear this from me, but nobody's going to come check on what you're doing with it, so don't ask permission for every little thing."

Getting the key changed less than any of them expected it to, in the moment, and more than they were ready for, in the months that followed. The lock still stuck when Dennis first tried it, rust having done its work over six unattended years. The gate still groaned like it hadn't opened in a long time, which it hadn't. But standing just inside it for the first time — three people who'd shared nothing but a nodding acquaintance a month earlier, now holding a single key between them — none of them said much of anything for a while. They just stood there, looking at what they'd taken on, weeds up past their knees in places, broken glass catching the afternoon light exactly the way it always had from the outside, except now it was theirs to deal with. There was a lot of work ahead, more than any of them had fully reckoned with yet, and none of it was going to be quick.$$
where chapter_number = 1
  and story_id = (select id from public.stories where title = 'The Community Garden');

update public.story_chapters
set body = $$Clearing the lot took longer than any of them had guessed, and none of them had guessed it would be quick. The weeds came out first, or were supposed to — root systems deeper and more stubborn than seemed reasonable for plants nobody had ever watered on purpose, some of them requiring a shovel just to loosen enough to pull, Rosa's gloves shredded through within the first weekend.

Underneath the weeds was worse. Broken concrete in slabs too heavy to lift without a truck, which meant a genuinely awkward series of phone calls trying to find out whether the city would haul it away for free or whether they'd need to pay out of pocket, a question that took two more weeks to resolve in their favor. The three shopping carts turned out to be rusted enough that they came apart in pieces rather than being wheeled out whole, each one a small unpleasant surprise of collapsing metal. And near what must have once been the back corner of the old auto shop, a scatter of nails and broken glass fine enough and dense enough that Yusuf insisted on a full second pass with a magnet on a stick, twice, before he'd agree that any child could safely be brought near the place.

Two weekends in, they had cleared maybe a third of it, and Dennis, sunburned across the back of his neck and sore in muscles he apparently hadn't used since retiring from driving a bus, said out loud what all three of them had clearly been quietly thinking. "I did not know this was going to be a full-time job." Rosa, straightening up from a particularly stubborn root system, just laughed, the tired kind of laugh that comes out when a complaint is too true to argue with.

They argued more than any of them expected to, for people who'd started this as a favor to the neighborhood rather than to each other, before they'd become anything like the friends they'd eventually become. Rosa wanted flowers along the fence line, something that would make the place look cared for and inviting from the street, something a passerby would notice and feel good about rather than just another vacant lot with plants in it. Yusuf, practical to a fault, wanted every inch of usable soil going to vegetables, arguing more than once, with real heat in his voice, that a garden that didn't feed anyone wasn't much of a garden, just decoration, and decoration wasn't worth this much backbreaking labor.

"You can't eat a marigold," he said, more than once, in what became something of a running joke between them by the second month, trotted out whenever the flowers-versus-vegetables debate resurfaced, which it did with some regularity.

"You can't look at a squash and feel like your street is somewhere worth living," Rosa shot back the first time, and meant it, though she said it with enough of a smile that Yusuf knew it wasn't really a fight, just a real disagreement they'd have to actually settle rather than paper over.

Dennis, mostly, wanted to stop arguing and start planting something, anything, before the season got away from them entirely, watching precious spring weeks tick by while the other two debated. They compromised eventually, in the way people do when nobody's fully satisfied but everyone's tired of arguing — flowers along the fence line where Rosa wanted them, vegetables filling the larger central plot where Yusuf's practicality won out, and a smaller patch near the gate left entirely undecided because none of them had the energy left to fight about it after everything else had finally been settled.

They planted late, later than any of the gardening books Yusuf had checked out from the library recommended for their climate zone, and it showed almost immediately. A heat wave arrived three weeks after the first seedlings went into the ground — ten straight days over ninety degrees that none of them had seen coming in the forecasts they'd half-heartedly checked, and that none of the young plants, barely established, were remotely ready for.

Rosa came by every single morning before work to water, arriving at six-fifteen with a watering can that felt increasingly inadequate against the heat, and again every evening after, sometimes bringing her daughter along, who found the whole enterprise fascinating in the specific way seven-year-olds find dirt fascinating. She still lost half of what she'd planted along the fence by the end of that stretch, wilted things she'd checked on hopefully each morning only to find a little more collapsed than the day before.

Yusuf's careful, methodically-planned vegetable rows fared a little better, benefiting from his insistence on proper spacing and mulching that the others had rolled their eyes at during the planning arguments, but only a little better — enough plants survived to feel like partial vindication rather than total loss, which was cold comfort against the visible gaps in what should have been full rows.

Dennis, checking on things one particularly brutal afternoon when the thermometer on his own porch had read ninety-six degrees in the shade, found himself standing in the dead center of the wilting lot saying something not especially polite to a sky that showed no signs of listening or caring, a moment Rosa happened to witness from the gate and never let him forget afterward.

Other neighbors watched all of this with open, sometimes vocal skepticism. A man two houses down, retired like Dennis but considerably less inclined toward new projects, told Rosa one morning, not unkindly but with real conviction, that he gave the whole enterprise until the first frost before everyone lost interest and the lot went back to weeds, same as always. A woman walking her dog past the fence most mornings asked, more than once, in a tone that suggested she already suspected the answer, whether they actually knew what they were doing. Rosa didn't entirely disagree with her, some days, watching another seedling fail to recover from the heat.

But something else was happening alongside all the losses that summer, slower and less visible than a heat wave, easier to miss if you were only counting surviving plants. The group chat the three of them had started just to coordinate watering schedules had grown, without anyone quite deciding to add people, from three names to nine — an older man from around the corner who turned out to know more about composting than any of them combined and showed up one Saturday with a truckload of his own finished compost, unprompted; two teenage brothers from down the block who'd started showing up after school with nothing better to do and stayed because pulling weeds turned out to be strangely satisfying once you got into a rhythm; a woman two streets over who brought lemonade some Saturdays for whoever was working and, the third time she brought it, simply stayed afterward to help pull weeds herself, lemonade jug still sitting untouched on the low wall by the gate.

By the end of that first difficult season, there wasn't much to point to in the lot itself if you were being strictly honest about it. A few surviving vegetable plants scattered through gaps where others had failed. Some flowers along the fence line, fewer than Rosa had hoped for but more than the skeptics had expected. A lot of bare, disturbed dirt where things simply hadn't made it through the heat. Sore backs that took most of the winter to stop aching. A season's worth of genuine arguments about spacing and watering schedules and whether marigolds served any purpose beyond looking nice.

What there was, though, that hadn't existed in June, was a list of nine names in a phone that had started as three, and a habit, hard-won across a difficult and often discouraging summer, of simply showing up, day after day, whether or not that day's efforts amounted to anything visible yet.$$
where chapter_number = 2
  and story_id = (select id from public.stories where title = 'The Community Garden');

update public.story_chapters
set body = $$Nobody had expected much from the second spring, not after how thoroughly the first season had gone sideways. Rosa, if she was honest with herself walking down to the lot that first warm week of March, had gone into it bracing for another summer of losses, another round of the man two houses down reminding her, not unkindly but not exactly kindly either, that he'd predicted this would fizzle out by now.

Instead, the tomatoes came up almost too easily, as if the ground itself had needed a full year to recover from being forgotten for six, to remember how to support something growing in it. Rows planted by people who, twelve months earlier, hadn't known each other's names came in thick enough by early June that there was surplus to give away before the month was even over — paper bags of tomatoes left on porches up and down the block with handwritten notes that just said "from the garden," more than the nine names in the group chat could possibly use themselves even accounting for the two teenage brothers' apparently bottomless appetite for anything they'd helped grow.

Word spread the way it does on a block where everyone's suddenly paying more attention to each other than they used to, where a shared project becomes an excuse for conversations that wouldn't otherwise happen. The man who'd given the project until the first frost, and who'd been quietly proven wrong when the frost came and went and the group chat kept growing anyway, showed up one Saturday morning with a shovel he'd apparently owned the whole time and never mentioned, offering to help expand the vegetable rows before anyone had to ask him twice, a small unspoken concession that he'd been wrong and wasn't going to make a big production out of admitting it.

The woman who walked her dog past the fence every morning, who'd once asked pointedly whether they knew what they were doing, started stopping instead of just passing through, leaning against the fence to chat while her dog sniffed at the gate. Within a few weeks she'd started bringing seedlings from her own backyard to add to the mix — extra tomato starts she'd grown too many of, a rosemary bush that had outgrown its pot, contributions offered almost shyly at first and then, once accepted warmly, with real enthusiasm.

Kids from the block began stopping by after school not because anyone had organized an activity for them, no formal program or scheduled hours, but because the garden had become, without any real planning on anyone's part, the most interesting thing within walking distance of the elementary school two blocks over — a place with actual dirt to dig in, tomatoes worth checking on daily to see how much redder they'd gotten, and, on the better afternoons, someone around willing to explain patiently why the squash plants were doing that strange thing with their leaves, or how to tell when a pepper was really ready to pick versus just looking ready.

Dennis, who less than a year earlier had stood cursing at the sky in the dead center of a dying lot, found himself most evenings now sitting on an upturned plastic crate near the gate instead of alone on his own porch two doors down, coffee going cold in his hand the same as always, except now there were usually two or three other people there to talk to while it did, kids weaving around the rows nearby, the low hum of actual neighborhood life happening in a space that had been silent and fenced off for six years before any of this started.

Yusuf's insistence on vegetables over flowers had, in the end, mostly won out in terms of sheer square footage, though Rosa's fence line bloomed thick enough by midsummer — helped considerably by the dog-walking woman's contributions — that even Yusuf privately admitted, though he'd never quite say it to Rosa's face in so many words, that it made the whole place look less like a construction site and more like somewhere you'd actually want to spend an evening. The undecided patch near the gate, left unplanted the year before out of sheer collective exhaustion by the time anyone got around to it, became instead a small bench area — two mismatched chairs someone had donated and a low wooden table one of the teenage brothers' father had built in his garage over a weekend, unprompted, once he'd heard how much time his sons were spending at the place. It became, almost immediately, the closest thing the garden had to a formal gathering spot, the place where the Saturday lemonade got set down, where end-of-day conversations happened as the light went gold and long across the rows.

The fence gate itself stopped getting locked during the day sometime that second summer, nobody quite deciding this all at once so much as it simply happening — propped open with a brick nobody specifically remembered placing there and nobody bothered to remove, a small unofficial statement that the lot belonged to the block now in a way that made a padlock feel beside the point. It just seemed to belong that way, the way certain small arrangements settle into a place once enough people agree, without ever explicitly discussing it, that they work better left alone.

There was a particular Saturday in July that Rosa still thinks about sometimes — nothing especially dramatic happened, which was rather the point. A dozen or so people ended up at the garden that afternoon without anyone organizing it, drawn in one by one over a few hours: the teenage brothers showing off a especially large tomato to anyone who'd look, the composting neighbor holding court about soil pH to Yusuf, who for once was the one being lectured rather than doing the lecturing, Dennis's crate occupied by someone else while he leaned against the fence instead, Rosa's daughter and two other kids from the block chasing something invisible between the rows, shrieking with the specific joy of children who've found an outdoor space that feels entirely their own. Someone brought a speaker. Someone else brought more lemonade than the first Saturday ever had. It wasn't a planned event. It was just, by that point, what the garden had become capable of producing on an ordinary weekend, given enough time and enough people who'd decided to keep showing up.

None of it looked like much from the street, if you were the kind of person who measured a garden's worth by how it might photograph for some magazine. Uneven rows that never quite matched the neat diagrams in Yusuf's original planning notes. A fence with paint that had chipped the first winter and never gotten properly touched up despite several stated intentions to get to it eventually. Tomato cages that leaned at increasingly dramatic angles under the sheer weight of what they were holding up by August. But it was full, most afternoons that second summer, in a way the lot had never once been full of anything in the six long years before three near-strangers decided, almost on a whim at a stop sign, to ask the city for a key.

Rosa still thinks about that stop sign conversation sometimes, the half-joke that started all of it — somebody ought to just take that fence down. She hadn't meant it as an actual plan when she said it, hadn't expected Dennis to do anything with it beyond a polite laugh. Neither had he, laughing along at first before something in him stopped laughing and started actually wondering why not. It had taken a full, discouraging, often exhausting season of failure before any of it really worked, tomatoes lost to heat and arguments won and lost about marigolds, and even now, watching it thrive the way it finally had, she understood that what had actually grown there wasn't really, in the end, about the tomatoes at all.$$
where chapter_number = 3
  and story_id = (select id from public.stories where title = 'The Community Garden');

-- ========== THE CROSSING GUARD (everyday_heroes) ==========
update public.story_chapters
set body = $$She took the job the year her youngest started kindergarten, meaning to do it for a season or two — a little extra money on top of what her husband brought home, a reason to already be near the school when the day ended instead of rushing over from somewhere else, something to fill the strange new quiet of mornings once all three of her kids were finally old enough for class and the house emptied out in a way it never had before. Twenty-two years later, she was still there, standing at the same corner, and the youngest who'd started it all had kids of his own now, crossing entirely different streets in a different part of town, a fact that still occasionally startled her when she let herself think about it directly.

The corner itself hadn't changed much in all that time, not really, not in any way that mattered — a four-way intersection two blocks from the elementary school, busier than it looked on a map because it caught the overflow from a bigger road half a mile down whenever that road backed up during rush hour. Cars came through faster than the posted speed limit technically allowed, especially in the first stretch of morning before the school buses arrived and slowed everyone down out of sheer necessity. It was, by any reasonable measure, not a glamorous corner to spend three hours of your morning and two hours of your afternoon standing on, in every kind of weather the region could produce, for over two decades running.

She learned early, within that first uncertain month, that the job was mostly about being visible and being early, about showing up consistently enough that the corner came to expect her the way it expected the sunrise. Fifteen minutes before the first kids usually started arriving, rain or shine or the handful of genuinely brutal winters that stretch of the country occasionally produced, she was out there in her reflective vest, flag in hand, orange bright enough to cut through fog on the worst mornings when visibility dropped to almost nothing past the far curb. She kept a small folding umbrella clipped to her bag for the first several years before finally investing in a proper rain poncho, a decision prompted by one particularly memorable September storm that soaked through three layers of clothing before the first bell even rang, leaving her squelching in her shoes for the rest of that entire shift.

The first year was the hardest, in ways she hadn't fully anticipated going in, thinking the job would mostly just be standing and waving. She didn't know any of the kids yet, didn't know which ones would dart ahead of a parent's outstretched hand the second they spotted a friend already on the other side, didn't know the rhythms of the corner — which mornings the buses tended to run late and threw off the whole flow of foot traffic, which specific drivers cut the corner too close on their way to work and needed an extra sharp whistle to slow down, which kids needed a little more time getting across because of a limp, or a heavy backpack that threw off their balance, or simply being small for their age and needing smaller, more careful steps than the older kids around them. She learned all of it slowly, the unglamorous way you learn anything — by simply doing it, imperfectly, every single day until it gradually stopped being unfamiliar and started being instinct.

There was a particularly brutal February in her fourth year on the job, an ice storm that coated the whole intersection in a treacherous glaze for the better part of a week, when the school considered closing entirely but ultimately didn't, leaving her to manage the corner in conditions that made even standing upright a genuine challenge. She remembers gripping the stop sign pole with one hand for balance while directing kids across with the other, remembers a particular gust of wind that nearly took her flag out of her grip entirely, remembers thinking, that week, that this job asked more of her than anyone watching from a car window during a normal morning would ever guess.

By the second year, she knew most of the regulars by sight even before she'd learned all their names — the tall boy who always ran the last twenty feet no matter how many times she reminded him, gently but repeatedly, not to; the pair of sisters who walked at exactly the same measured pace every single morning as if they'd rehearsed it, matching stride for stride without seeming to notice they were doing it; the quiet kid who hung back at the edge of whatever group had gathered and crossed last, every single day, as if he were in no particular hurry to arrive wherever the day was about to take him.

She started learning names properly around the third year, once it became clear to her, and to the neighborhood, that this wasn't going to be a temporary arrangement after all — first names initially, and eventually, for the families who stayed on her route long enough, younger siblings' names too, learned before the sibling in question was even old enough to walk to school themselves, filed away for whenever they eventually showed up at her corner for the first time, small and nervous, holding an older sibling's hand.

Parents started recognizing her as a genuine fixture of the neighborhood rather than simply a stranger doing an assigned job, would slow their cars to roll a window down and say good morning by name, would occasionally stop altogether, engine idling, to ask if she'd noticed anything about their kid lately that they perhaps ought to know about — a question that always struck her as slightly strange the first few times she got it, and then, over the years, came to feel like one of the most important parts of a job that had started out sounding simple.

She hadn't expected that part of it, honestly, hadn't seen it coming when she signed up all those years ago mostly for the extra money and the convenient proximity to her kids' school. Being trusted with more than just getting children safely from one curb to the other, being treated as some kind of extended, unofficial set of eyes on an entire generation of kids. But it made a certain kind of sense the longer she actually did it, the longer she stood there morning after morning watching the same faces arrive and depart in a rhythm that eventually became as familiar to her as her own heartbeat. She was there every single school day, watching closely, in a way that even the most attentive and loving parents sometimes weren't, caught up as they inevitably were in the daily scramble of getting everyone dressed, fed, and out the door on time. She noticed things almost by accident, the way you notice anything you're paying real attention to over enough repeated mornings: a kid who seemed a little slower to smile than he usually was, a backpack carried in a way that suggested it weighed more, physically or otherwise, than it should have, a flinch at a car horn or a raised voice nearby that seemed sharper and more instinctive than the moment on its own would have called for.

Nobody had trained her to watch for any of that, not really. It certainly wasn't covered in whatever brief orientation the school district had given her twenty-two years earlier, a single afternoon in a stuffy conference room covering proper hand signals, liability paperwork, and the correct way to hold a stop sign paddle so drivers couldn't claim they hadn't seen it. She just did it anyway, the way you do anything you've come to genuinely care about over a long enough stretch of time — not because any job description required it of her, but because she was already standing there every morning regardless, already paying close attention out of habit, and it would have taken more deliberate effort at that point to look away than it ever took to simply keep noticing.$$
where chapter_number = 1
  and story_id = (select id from public.stories where title = 'The Crossing Guard');

update public.story_chapters
set body = $$There was a boy, early on in her second decade at the corner, who started showing up some mornings in the same shirt he'd clearly worn the day before, a little quieter than she remembered him being at the start of that particular school year, a little slower to meet her eyes when she offered her usual cheerful greeting. She didn't say anything the first time she noticed, or the second, not wanting to embarrass him over something that might have had a perfectly ordinary explanation. By the third time, though, a pattern rather than a coincidence, she found herself asking, as gently and casually as she could manage, whether everything was okay at home — not prying exactly, just leaving a door open in case he wanted to walk through it in his own time.

He didn't, not that particular morning. He just shrugged and mumbled something noncommittal and crossed the street a little faster than usual, as if eager to end the conversation. But two weeks later, waiting together for a gap in a stubbornly steady stream of traffic, he mentioned almost sideways, looking at the cars rather than at her, that his dad had moved out recently, that mornings were different now in ways he didn't fully have words for yet, that his mom cried sometimes before he left for school and he didn't always know what he was supposed to say to her when that happened, being only eight years old and entirely unequipped for that particular kind of responsibility.

She listened, mostly, the way you listen to a kid who needs to say something out loud far more than he actually needs a response back, nodding along, not rushing to fill the silences he left, letting him get out what he needed to get out before the light changed and it was time to actually cross. She told the school counselor what he'd shared with her later that same day, carefully, in the vaguest possible terms that would still get the right people paying appropriately close attention without betraying the specific trust he'd placed in her, and she never once mentioned to the boy himself that she'd passed anything along. He seemed steadier within a few weeks, whatever combination of factors — home, school, simple time — had contributed to that. She never learned exactly what had changed for him, only that something clearly had, and she liked to think, without needing confirmation, that her small nudge in the right direction had been some quiet part of it.

There were other names, other mornings, that stayed with her over the many years in that same particular way, small interventions that never felt dramatic in the moment but that she carried with her long afterward. A girl who went unusually quiet and watchful for a stretch one particularly hard winter, until it eventually came out — not directly to the crossing guard, in this instance, but through a worried friend who mentioned it to her at the corner one morning — that things had gotten genuinely difficult at that girl's home in a way that needed more than just a kind word at a crosswalk to address, prompting another careful, anonymous-feeling word to the school. A boy who started arriving some mornings without having had any breakfast, which she noticed specifically because he'd occasionally get visibly lightheaded waiting at the corner, swaying slightly on his feet in a way that worried her, and which she solved, quietly and without any fanfare, by simply keeping a small box of granola bars zipped into the front pocket of her bag for the better part of a full year, handing them over with no explanation needed or offered, until whatever situation had caused the gap at home seemed to resolve itself on its own.

None of these small interventions ever felt dramatic to her, even at the time, and she would have been genuinely uncomfortable being called any kind of hero for any single one of them. What she actually did, mostly, boiled down to noticing, consistently and carefully, and then saying something small and low-stakes enough that a kid or a worried parent could take it or leave it entirely without ever feeling exposed or judged for needing the help in the first place. "Everything okay?" cost her nothing to ask, and cost the person being asked nothing to answer honestly or not as they saw fit, and she'd learned, over literally thousands of mornings of practice, exactly how to ask it so it never once felt like an interrogation, just an open door left quietly ajar.

She kept, without ever writing any of it down, a running mental catalog of which kids needed a little extra unhurried time crossing, which ones responded well to a joke first thing to get them smiling before the rest of their school day even started, which ones needed to be left entirely alone on certain mornings because even kind, well-meaning attention made things harder for them rather than easier on the days their nerves were already frayed before they'd even reached her corner. She adjusted her whole approach, corner interaction by corner interaction, kid by kid, year after year, building out an entirely unofficial curriculum that nobody had ever formally handed her and that existed only because she'd chosen, morning after morning for over two decades, to pay closer attention than the job on paper ever strictly required of her.

Parents noticed all of this too, eventually, in ways that occasionally surprised her when they said so out loud. A mother stopped her directly one ordinary Tuesday morning, car idling at the curb, specifically to thank her for having asked her son, some months back, about a rough patch the whole family had been quietly struggling through, telling her it had apparently meant far more to him at the time than anyone at home had fully realized until he mentioned it himself, weeks later, almost in passing. A father, dropping his daughter off on what turned out to be his very last morning before a lengthy military deployment overseas, pulled her aside specifically to ask, with real seriousness in his voice, if she would keep an extra careful eye on his daughter while he was away, treating her, in that moment, as genuinely and seriously as he might have treated any other trusted member of the family's actual support network.

She had started this job twenty-two years earlier thinking of it, if she was honest, as little more than a convenient way to stand near a school for a few paid hours each day. Somewhere in the accumulated middle of all those thousands of individual mornings, without her ever consciously deciding it should become anything more, it had quietly turned into something closer to a genuine, unofficial form of ongoing care for an entire rolling generation of children on that particular block — each one noticed, carefully and consistently, one crosswalk at a time, by someone whose actual official job description had never once, in over two decades, mentioned any single part of it.$$
where chapter_number = 2
  and story_id = (select id from public.stories where title = 'The Crossing Guard');

update public.story_chapters
set body = $$She'd expected her very last morning on the job to be a quiet one, mostly — a final routine wave at the corner, maybe a small sheet cake waiting in the school office afterward if the staff remembered to organize one amid everything else going on that week, and then the strange, sudden absence of a routine that had shaped every single school-year morning of her adult life for twenty-two consecutive years running.

Instead, she arrived at her usual time that morning, fifteen minutes ahead of the first expected kids as always, to find nearly two dozen people already gathered at the corner well ahead of her, spilling out onto both sidewalks in a way that briefly made the actual business of crossing the street more complicated than usual, cars slowing in visible confusion at the unexpected crowd. Some of the people gathered were current parents she saw and greeted every single school day. A great many more of them, she realized as she got closer and started actually recognizing faces, were not current parents at all.

There was a young man, easily in his late twenties now, someone she placed after only a moment as the boy who used to run the last twenty feet of every single crossing no matter how many times over the years she'd gently told him not to, now standing there with a toddler of his own balanced on one hip, waiting his turn to cross that exact same corner for what was apparently the first time as a parent himself. There were the two sisters, fully grown now, who used to walk at precisely the same measured pace every single morning without seeming to notice they were doing it, and who apparently still moved in that same unconscious unison crossing the street together as adults, a detail that made her throat tighten slightly when she noticed it. There was the quiet boy who'd always hung back at the edge of the group and crossed last, every single day without exception — taller now, considerably more confident in the way he carried his own shoulders, holding a card in one hand that had clearly been made by his own hand rather than purchased anywhere.

She hadn't told anyone beyond the school office the specific date of her last day, hadn't wanted any particular fuss made over what felt to her like simply the natural end of a long, ordinary run. Someone, evidently, had asked around anyway, and word had traveled the way it inevitably does in a neighborhood that had spent well over two decades quietly getting used to the idea that she was a genuine fixture of the community rather than merely an employee performing an assigned task.

The handmade cards came to her one at a time over that final quarter hour, more of them than she could possibly read all the way through before the first bell actually rang and the crossing had to properly begin. Most were simple and sweet in the specific way children's cards always are — heartfelt thank-yous in wobbly handwriting, a number of surprisingly recognizable crayon drawings of a woman in an orange vest holding a flag, the particular visual signature of someone who'd apparently been drawn, with real affection, by successive waves of schoolchildren for over twenty years running without her ever quite realizing it. A handful of the cards were considerably longer, written by the parents themselves rather than by their kids: heartfelt notes describing a genuinely hard year that had somehow gotten a little more bearable because someone reliable showed up every single morning and quietly noticed when something wasn't right, notes recalling one specific brief conversation at that exact corner that had apparently mattered far more, in the end, than she'd ever fully realized in the moment it actually happened.

The boy who used to arrive some mornings without any breakfast, a father himself now by the look of the toddler on his hip, told her directly, right there in front of the assembled crowd, about the box of granola bars she'd once kept zipped in her bag for the better part of a year specifically on his account — a small detail she'd genuinely half-forgotten until the very moment he brought it up again, and one he had evidently, quietly, never forgotten at all in the years since. "I don't think you ever really knew just how bad things actually were at home for us that particular year," he told her, his voice noticeably unsteady. "But you fed me anyway, every single morning, without ever once making a whole thing out of it in front of anyone. I've thought about that more than you'd probably guess."

She didn't have any kind of formal speech prepared, hadn't anticipated needing one for what she'd assumed would be an unremarkable final morning. She said something simple instead, close in tone and substance to what she might have said to any of them on any perfectly ordinary morning at that same corner over the preceding twenty-two years: that she was deeply glad to have gotten to know every single one of them over the years, that watching an entire generation of this neighborhood's kids grow up, one careful crossing at a time, had turned out to be, without question, the best part of a job that most outside observers had probably always assumed was a fairly small and unremarkable one.

Someone near the back of the gathered crowd asked, just as the first bell rang faintly in the distance, whether she had any parting advice for whoever the district assigned to take over her corner next. She considered the question seriously for a moment, flag still gripped in her hand out of sheer twenty-two-year habit even though there was no traffic yet actually requiring it, and gave the only answer that felt entirely true to her. Learn every one of their names as quickly as you possibly can, she said, and then just keep showing up, morning after morning, even on the days it doesn't feel like it matters much. Especially on those days, actually.

Most people passing through, she's always known and accepted without much bitterness about it, don't really notice a crossing guard at all — just another small fixture at the edge of an ordinary school morning, easy enough to drive past without a second glance on the way to wherever they're actually headed. For twenty-two full years, standing at that same unremarkable corner in every kind of weather the region could produce, she had quietly made a consistent practice of noticing every single one of them back, regardless of whether anyone ever noticed her in return. On her very last morning standing at that corner, it turned out, rather movingly, that they had all been quietly noticing her the entire time too.$$
where chapter_number = 3
  and story_id = (select id from public.stories where title = 'The Crossing Guard');
